version: "3.7"

services:
  # Define a Telegraf service
  telegraf:
    image: telegraf:1.19
    volumes:
      - ./src/main/resources/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - 8125:8125/udp
    networks:
      - spring-forum-network
    depends_on:
      - influxdb
  # Define an InfluxDB service
  influxdb:
    image: influxdb:1.7
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
    networks:
      - spring-forum-network
  # Define a Chronograf service
  chronograf:
    image: chronograf:1.6
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - KAPACITOR_URL=http://kapacitor:9092
    ports:
      - 8888:8888
    networks:
      - spring-forum-network
  # Define a Kapacitor service
  kapacitor:
    image: kapacitor:1.5
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    ports:
      - 9092:9092
    networks:
      - spring-forum-network

networks:
  spring-forum-network: